---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Song.
--- DateTime: 2019/1/22 11:43
---

local UIManager = class('UIManager', 'UClass')

function UIManager:init()
    print('UIManager.init')
end

return UIManager