---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Song.
--- DateTime: 2019/1/22 10:05
---
require('CleverCreator/Library/Global')
require('CleverCreator/Library/Class')
require('CleverCreator/Library/UClass')

require('CleverCreator/UI/BaseWidget')

CleverCreator = {}

local CleverInstance_C = require('CleverCreator/Core/CleverInstance')
local SceneManager_C = require('CleverCreator/Scene/SceneManager')
local UIManager_C = require('CleverCreator/UI/UIManager')

---@param instance userdata
function CleverCreator_Init(instance)

    ---@class CleverCreator
    local Instance = CleverInstance_C(instance)
    CleverCreator.Instance = Instance

    ---@class SceneManager
    SceneManager = SceneManager_C(Instance:GetSceneManager())

    ---@class UIManager
    UIManager = UIManager_C(Instance:GetUIManager())

    UIManager:OpenGroup('Loading')
end