---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Song.
--- DateTime: 2019/1/22 10:05
---
require('CleverCreator/Library/Class')
require('CleverCreator/Library/UClass')

CleverCreator = {}

local CleverInstance_C = require('CleverCreator/Core/CleverInstance')
local UIManager_C = require('CleverCreator/UI/UIManager')

---@param instance userdata
function CleverCreator_Init(instance)

    local Instance = CleverInstance_C(instance)
    CleverCreator.Instance = Instance

    ---@class UI管理
    UIManager = UIManager_C(Instance:GetUIManager())

    UIManager:OpenGroup('Loading')
end