---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Song.
--- DateTime: 2019/1/22 10:21
---

---@class CleverInstance
local CleverInstance = class('CleverInstance', 'UClass')

function CleverInstance:init()
    print('CleverInstance.init')
end

return CleverInstance