---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Song.
--- DateTime: 2019/1/23 11:10
---

local Demo = class('Demo', 'BaseWidget')

function Demo:construct()
    print('Demo:construct')
end

function Demo:destruct()
    print('Demo.destruct')
end

function Demo:onOpen(param)
    print('Demo.onOpen', param)
end

function Demo:onClose(param)
    print('Demo.onClose', param)
end

return Demo